app:
  build: .
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db

db:
  image: mongo
  hostname: mongo
  environment:
    - MONGO_INITDB_DATABASE = test
  ports:
    - 27017:27017
